export const todoActionType = {
  ADD: "ADD_TODO",
  TOGGLE: "TOGGLE_TODO",
  FETCH_TASKS_PENDING: "FETCH_TASKS_PENDING",
  FETCH_TASKS_SUCCESS: "FETCH_TASKS_SUCCESS",
  FETCH_TASKS_ERROR: "FETCH_TASKS_ERROR",
};
export const todoFilterActionType = {
  SET_FILTER: "SET_FILTER",
};
export const authActionType = {
  TOGGLE_SIGNUP: "TOGGLE_SIGNUP",
  FETCH_PENDING: "FETCH_PENDING",
  FETCH_LOGIN_SUCCESS: "FETCH_LOGIN_SUCCESS",
  FETCH_SIGNUP_SUCCESS: "FETCH_SIGNUP_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
};
