export const todoActionType = {
  ADD: "ADD_TODO",
  TOGGLE: "TOGGLE_TODO",
  FETCH_TASKS_PENDING: "FETCH_TASKS_PENDING",
  FETCH_TASKS_SUCCESS: "FETCH_TASKS_SUCCESS",
  FETCH_TASKS_ERROR: "FETCH_TASKS_ERROR",
};
export const todoFilterActionType = {
  SET_FILTER: "SET_FILTER",
};
